### ISSUE TITLE
guillemets dans les balises <a>

### ISSUE THREAD

**Issue by sebastienserre** [webaxones/spte#2]
Glotdict signale les " autour des URL dans les balises <a>.
Aurais tu pas moyen de masquer cette alerte dans ce cas ?

**Comment by webaxones** [comment]
Hier soir j'ai cherché désespéremment ce que faisait GlotDict sur les guillemets et je viens ce matin de comprendre que tu voulais parler de SPTE :D 
Oui, il faut que je gère ça tu as raison.
