### ISSUE TITLE
Revoir le libellé de l'option "Cocher les avertissements en rouge"

### ISSUE THREAD

**Issue by fr-laurentn** [webaxones/spte#36]
![image](https://user-images.githubusercontent.com/15927630/103454103-d7b0b700-4ce0-11eb-86f4-8775f115dc30.png)

Le libellé de cette option pose plusieurs problèmes :

- Il n'est pas accessible aux personnes daltoniennes
- Il n'est pas très explicite : que signifie la couleur rouge ? Est-ce qu'il s'agit d'une erreur de glossaire ? De typo ? De ponctuation ?
- Il crée de la confusion avec le rouge utilisé par GlotDict pour signaler de manière générale une chaîne contenant une erreur (peu importe le type d'erreur).
Ainsi, sur la capture d'écran si dessous, je ne sais pas à quel rouge tu fais référence : 
![image](https://user-images.githubusercontent.com/15927630/103454199-e9df2500-4ce1-11eb-980d-d15e6bc69492.png)

Lors de nos échanges sur Slack tu m'avais indiqué que les couleurs correspondaient à un niveau d'importance, avec une marge d'erreur.

Suggestion : pour éviter tout doute et toute subjectivité (qu'est-ce qui permet de dire qu'une erreur est plus importante qu'une autre ?), je propose que le code couleur corresponde à une typologie d'erreur.
Ainsi, c'est quelque chose de factuel et qui ne nécessite pas de voir la couleur pour comprendre de quoi il s'agit.

D'avance merci

**Comment by webaxones** [comment]
![image](https://user-images.githubusercontent.com/17084006/103584030-2036c300-4ee1-11eb-8224-fc1339b87d2a.png)

Merci @fr-laurentn d'avoir relevé ce problème qui n'est pas limité à cette case à cocher.
Je reviens sur le pourquoi des couleurs d'abord afin que l'on ait moyen de trouver une solution en adéquation.
SPTE repère 3 types d'erreurs : 

1. les apostrophes droites
2. les mots mal orthographiés ou déconseillés par le glossaire
3. les caractères ne respectant pas les règles typographiques

Ces 3 analyses sont inégales en terme de fiabilité : 
Les valeurs que j'ai estimés sont probablement fausses mais c'est du à peu près.
Parce qu'une apostrophe droite sera à 99% fausse, à moins de certains cas très très rares.
Idem pour les mots, avec quelques exceptions ultra rares comme dans les noms d'extensions (mais je compte lever l'exception).
Par contre pour les caractères, c'est encore à travailler, et même si j'aimerais atteindre le 99%, pour l'instant les exceptions sont encore là. Donc j'ai estimé un 70%. C'est peut-être plus, peut-être moins.
![couleurs](https://user-images.githubusercontent.com/17084006/103582945-21ff8700-4edf-11eb-8d0e-f943068e3413.png)

Au tout début, SPTE ne remontait qu'un seul type d'erreur. Donc la couleur rouge m'était venue naturellement puisque c'est le code couleur international pour les panneaux de signalisation. Le rouge sang signifie STOP, ou ATTENTION.

Puis SPTE a remonté plus d'erreurs, et vu qu'il existait en gros 2 niveaux de fiabilité, j'avais gardé le rouge pour le top fiabilité, et réduit le rouge pour obtenir un rose pour la fiabilité moins sûre.

Mais le problème, c'est que le rouge n'est pas visible par tout le monde. Qu'il serait bien que les couleurs soient paramétrables en fonction de l'utilisateur, et problème adjacent, ça me pénalise dans les noms des champs : "cocher les avertissements en rouge" ça n'est pas satisfaisant. 
Mais le souci c'est que ça n'est pas aussi simple que ça. Par quoi remplacer "les avertissements en rouge" "les avertissement en rose". "Cocher les avertissements sur les mots et sur les apostrophes" c'est niet car l'interface est déjà blindée. Il faut du court. Ou au moins du pas trop long.

**Donc j'ai besoin de votre aide pour cogiter là dessus et me donner vos idées en commentaires de cette issue**
**La question est donc : si les couleurs deviennent paramétrables, par quelles appellations identifier le niveau de fiabilité ?**

(Concernant l'application des couleurs, c'est à dire la forme) je ne compte pas la remettre en question puisque c'est après beaucoup d'essais en CSS que j'ai remarqué que mettre en exergue un mot pouvait se faire avec juste une couleur de fond différente du fond de la cellule et une couleur de texte différente du fond du mot et du texte habituel, **mais** que ça n'était pas suffisant pour un caractère unique, et que pour que ce dernier se repère il fallait lui changer sa couleur de fond, sa couleur de texte mais aussi l'encadrer et de 2px et non 1 sinon les couleurs se mélangeaient, bref si quelqu'un un jour veut remettre ça en question je lui demanderai de venir avec un essai visible et non juste une idée :) )

**Comment by drixe69** [comment]
Cocher les avertissements majeurs

**Comment by sebastienserre** [comment]
En lisant, j'ai pensé a la même chose que @drixe69.
"avertissement majeur" / "Avertissement mineur" et les gens mettent les couleurs qu'ils veulent en face de chaque.

**Comment by webaxones** [comment]
@drixe69 & @sebastienserre 
J'y vois un défaut, surtout pour "mineur" : il ne s’agit pas d'avertissements mineurs, mais d'avertissements majeurs dont la fiabilité est moyenne.
Avertissements mineurs laisse entendre que ça n’est pas très grave de ne pas mettre une espace avant un point d’interrogation.
Or c’est interdit puisque cela génèrera un reject de la part d’un PTE. Par contre la fiabilité d’être dans un cas qui est interdit n’est pas certaine. C'est la fiabilité et non l’avertissement qui est spécifiée.

Idée/question : 
J'en arrive à penser que la fiabilité ne devrait pas être indiquée par une couleur. Qu’une précision déjà indiquée concernant les faux positifs possibles est suffisante.
Parce que : est-ce que l’on peut imaginer qu'SPTE arrive à maturité rapidement dans les mois à venir (à atteindre le 99% partout), je le pense. La dénomination pourrait alors se résumer à "avertissements". Je pourrais solutionner la longueur du sélecteur en remplaçant la coche automatique par un cocher tous + liste déroulante proposant : mots OU OU apostrophes OU caractères. Voire des associations mots + apostrophes, mots + caractères etc. Et là, je rendrais les couleurs paramétrables, MAIS par type d’erreur : il y aurait donc dans les paramètres 3 couleurs que l’on pourrait paramétrer, celle des mots, celle des apostrophes, celle des caractères.

**Comment by ePascalC** [comment]
Si je vois les catégories et que je pars de l'anglais, je penserais à: 
forte probabilité d'erreur / faible probabilité d'erreur

**Comment by webaxones** [comment]
Proposition de Paul : 
Fiabilité élevée, fiabilité moyenne

**Comment by fr-laurentn** [comment]
@webaxones désolé, mais je ne trouve pas ça clair. Seuls, ces messages n'ont pas d'intérêt et peuvent créer plus de confusion qu'autre chose. Ça implique quoi concrètement de savoir le degré de fiabilité ?

Si tu veux alerter les utilisateurs et utilisatrices du fait que l'outil ne remplace pas la vérification humaine, un simple message dans ce sens suffit. Pas besoin de se prendre la tête avec des degrés de fiabilité ^^

**Comment by webaxones** [comment]
Issue réglée avec la version 1.0.0.2 qui supprime les niveaux de fiabilité pour ne laisser que les types : mots, apostrophes, caractères

**Comment by fr-laurentn** [comment]
Merci @webaxones !
