### ISSUE TITLE
"Cocher les avertissements en rouge" ne coche pas toutes les lignes

### ISSUE THREAD

**Issue by sebastienserre** [webaxones/spte#37]
Hello,
La checkbox "Cocher les avertissements en rouge" ne coche pas les lignes avec espaces insacables manquants:
![non-cochee](https://user-images.githubusercontent.com/3902621/103575759-7a7c5780-4ed2-11eb-91f6-508f949c5220.png)

**Comment by webaxones** [comment]
Je ferme cette issue qui trouvera sa résolution dans la solution que l'on trouvera à la précédente
