### ISSUE TITLE
Faux positif : espace manquante avant/après quand il y a des balises HTML

### ISSUE THREAD

**Issue by Pierre-Lannoy** [webaxones/SPTE#39]
Hello !
Le cas suivant génère un faux positif : 

<img width="741" alt="image" src="https://user-images.githubusercontent.com/15095492/106357969-b061ff80-6309-11eb-803b-0988ff1731ed.png">

Si les balises HTML avaient été supprimées avant analyse, cela n'aurait pas été le cas...
Ça peut donc être une piste de solution 😄

**Comment by webaxones** [comment]
Normalement résolu avec la version 1.0.1 :)

**Comment by Pierre-Lannoy** [comment]
Super ! Thanks :)

**Comment by webaxones** [comment]
@Pierre-Lannoy En fait, j'ai suivi ton conseil (après avoir fortement râlé intérieurement) :D
