### ISSUE TITLE
entitée html non echappée

### ISSUE THREAD

**Issue by sebastienserre** [webaxones/spte#4]
[Lien Translate](https://translate.wordpress.org/projects/wp-plugins/awesome-support/stable/fr/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=5858936&filters%5Btranslation_id%5D=74945841)

SPTE m'encadre le `;` de `& #039;`

**Comment by webaxones** [comment]
Oui. Et c'est correct. Si l'entité HTML avait été écrite correctement sans espace après le & STPE n'aurait rien dit.
