### ISSUE TITLE
SPTE masque la ligne de recherche

### ISSUE THREAD

**Issue by papicx92** [webaxones/spte#40]
Quand j’active l’extension SPTE, elle masque la ligne de recherche dans les pages de https://translate.wordpress.org/projects
C’est Marie qui m’a mis sur la voie pour résoudre ce problème d’affichage. En désactivant l’extension (sur Firefox) la barre réapparait. 
Voir capture ci-dessous.
Serait il possible de résoudre cela, stp ? Merci d’avance.
![2021-03-16_191108](https://user-images.githubusercontent.com/80912550/111663903-89a44d80-8811-11eb-8d95-82f426b66e24.png)

**Comment by webaxones** [comment]
Bonjour Patrice,
Je ne dois pas comprendre le problème. Voici ce qui se passe sur mon firefox (et sur chrome) :
http://somup.com/creqi8bqMc
Si ça n'est pas la même chose sur le tien, peux-tu me détailler encore plus précisément ce qui ne fonctionne pas que je comprenne ? Tiens, fais moi une copie d'écran Avant Après, comme ça je verrai mieux.

**Comment by papicx92** [comment]
Bonjour Loïc.C'est bien simple, la ligne où il y a "Filter, sort, untransled, " etc. N'apparaît pas si l'extension est activée. Elle est présente si l'extension est désactivée. J'avoue que la présence du pointeur sur ma capture d'écran t'a sûrement induite en erreur sur l'objet de mon signalement. Je suis sur mon phone au travail, je ne peux donc pas faire de nouvelle capture. PapicxEnvoyé de mon Galaxy S8+ Free
-------- Message d'origine --------De : Loïc Antignac ***@***.***> Date : 19/03/2021  09:01  (GMT+01:00) À : webaxones/spte ***@***.***> Cc : papicx92 ***@***.***>, Author ***@***.***> Objet : Re: [webaxones/spte] SPTE masque la ligne de recherche (#40) 

Bonjour Patrice,

Je ne dois pas comprendre le problème. Voici ce qui se passe sur mon firefox (et sur chrome) :

http://somup.com/creqi8bqMc

Si ça n'est pas la même chose sur le tien, peux-tu me détailler encore plus précisément ce qui ne fonctionne pas que je comprenne ? Tiens, fais moi une copie d'écran Avant Après, comme ça je verrai mieux.

**Comment by webaxones** [comment]
Je n'arrive pas à reproduire le problème.
Quand tu seras sur ordi, est-ce que tu pourras me dire quand tu reproduis le problème : 

- si tu es connecté ou non à translate.wordpress.org et si tu es PTE ou traducteur sur le projet qui pose problème
- combien de lignes tu affiches par page (paramètre dans les settings de translate)
- un projet sur lequel tu reproduis l'erreur : si c'est un plugin et sur quel numéro de page avec quel nombre de lignes par page (voir question précédente)
- si ça le fait sur toutes les pages ou uniquement sur celles qui n'ont pas d'erreurs
- la résolution de ton écran peut-être

Bref : tous les éléments qui me permettront de reproduire le problème car en l'état je n'y arrive pas et sans pouvoir le reproduire je ne peux pas le corriger.
Merci

**Comment by papicx92** [comment]
Bonjour Loïc,
je suis sur mon pc.
Je suis avec Firefox 86.0.1 64 bits, sous Windows 10, connecté au site WordPress.org à la page https://translate.wordpress.org/projects/wp/dev/fr/default/ 
Quand l’extension spte est désactivée, je vois donc la ligne Filter, sort, All, etc 
Dès que j’active l’extension SPTE, la barre de recherche disparait. 
En actualisant la page, la barre réapparait furtivement. Voir la vidéo jointe. 
Je t’ai fait des captures d’écran comme tu me l’as demandé. 
NB : toutes les autres extensions, y compris Avast et Avast Password sont désactivées, seule SPTE est active. Si j’act
![spte désactivé](https://user-images.githubusercontent.com/80912550/111807489-46aaae80-88d3-11eb-9ff8-ef8d49a0fb83.png)
![spte désactivé_02](https://user-images.githubusercontent.com/80912550/111807492-47434500-88d3-11eb-9cf3-b683aa28c0ed.png)
![spte réactivé_03](https://user-images.githubusercontent.com/80912550/111807495-47dbdb80-88d3-11eb-8d04-10136e6bda38.png)
![spte réactivé_04](https://user-images.githubusercontent.com/80912550/111807497-47dbdb80-88d3-11eb-8859-cf3a935a818b.png)

https://user-images.githubusercontent.com/80912550/111807745-925d5800-88d3-11eb-9fcc-7315806cc071.mp4





ive les autres , j’ai les mêmes réactions.

**Comment by webaxones** [comment]
Ok donc en fait, ya pas que les filtres qui disparaissent mais aussi les numéros de pages à droite...
Je n'arrive toujours pas à le reproduire mais en sachant que ça masque et les numéros de page, et les filtres, je peux je pense arriver à trouver le cas spécifique où ça se produit.
Je te tiens au courant, cela ne sera pas corrigé demain malheureusement mais dès que je peux me pencher sur le problème je le corrige.

**Comment by papicx92** [comment]
Je n'avais pas remarqué le masquage des numéros de page... Pour info, ça reproduit sur tous les projets, pas seulement cette page précisément.J'ai essayé sur des pages de thème ou d'extensions, c'est pareil. PapicxEnvoyé de mon Galaxy S8+ Free
-------- Message d'origine --------De : Loïc Antignac ***@***.***> Date : 19/03/2021  17:26  (GMT+01:00) À : webaxones/spte ***@***.***> Cc : papicx92 ***@***.***>, Author ***@***.***> Objet : Re: [webaxones/spte] SPTE masque la ligne de recherche (#40) 

Ok donc en fait, ya pas que les filtres qui disparaissent mais aussi les numéros de pages à droite...

Je n'arrive toujours pas à le reproduire mais en sachant que ça masque et les numéros de page, et les filtres, je peux je pense arriver à trouver le cas spécifique où ça se produit.

Je te tiens au courant, cela ne sera pas corrigé demain malheureusement mais dès que je peux me pencher sur le problème je le corrige.

**Comment by jeherve** [comment]
Même chose de mon coté, sur Chrome chez moi.

**Comment by webaxones** [comment]
Bonjour Jérémy,
En tant que dév, pourrais-tu trouver 1 mn pour :
installer l'extension Storage Area Explorer https://chrome.google.com/webstore/detail/storage-area-explorer/ocfjjjjhkpapocigimmppepjgfdecjkb
qui ajoute un onglet dans l'inspecteur de code et 
- me donner les param storage enregistrés (les spte et peut-être les gd de glodict au cas où) même si je pense pas que ça vienne de ceux là.
- et surtout : ouvrir la page d'action des paramètres d'SPTE (la popup à partir de l'icône), faire clic droit inspecter et là me donner les paramètres d'SPTE enregistrés en chrome.storage.local (c'est pas le même, c'est le code de la page d'action)
Merci ! :)

**Comment by jeherve** [comment]
> me donner les param storage enregistrés (les spte et peut-être les gd de glodict au cas où) même si je pense pas que ça vienne de ceux là.

```
{
	"gd_no_non_breaking_space": "true",
	"gd_glossary_date": "",
	"gd_locales": "{\n    \"ast\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"bel\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"bn_BD\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"bg_BG\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"cy\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"da_DK\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"de_DE\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"en_AU\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"en_CA\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"en_GB\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"es_AR\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"es_ES\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"es_MX\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"es_VE\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"el\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"eu\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"fi\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"fr_FR\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"fr_CA\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"gu\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"he_IL\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"hi_IN\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"hr_HR\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"hu_HU\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"it_IT\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"ja\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"lt_LT\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"lv_LV\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"mr\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"ne_NP\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"nl_BE\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"nl_NL\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"pt\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"pt_BR\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"pl_PL\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"ro_RO\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"sk\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"sr\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"sv_SE\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"te\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"th\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"tr_TR\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"uk\": {\n        \"time\": \"13/04/2021\"\n    },\n    \"vi\": {\n        \"time\": \"13/04/2021\"\n    }\n}",
	"gd_language": "fr_FR",
	"gd_curly_apostrophe_warning": "true",
	"gd_locales_date": "13/4/2021"
}
```

> ouvrir la page d'action des paramètres d'SPTE (la popup à partir de l'icône), faire clic droit inspecter et là me donner les paramètres d'SPTE enregistrés en chrome.storage.local 

Pas sur d'être sur la bonne page, parce que pour moi c'est vide.


https://user-images.githubusercontent.com/426388/114583134-920d6e00-9c81-11eb-9ff6-6697b0c9324b.mov

**Comment by webaxones** [comment]
Non là tu es sur les options qui correspondent au browser action.
En fait, si tu cliques sur le puzzle dans la barre en haut, tu vas pouvoir épingler l'icône d'SPTE (qui se masque sur les sites hors translate). Ensuite tu peux ainsi cliquer sur l'icône SPTE (un stabilo rouge) et la popup des paramètres apparait. Et c'est sur cette popup qu'il faut inspecter le code et trouver les storage.
Merci pour les tests, je n'ai pas réussi à reproduire chez moi d'où la nécessité de reprendre exactement vos params pour débuguer :)

**Comment by jeherve** [comment]
ah oh. Ce sont les réglages par défaut :

```
{
	"spteSettings": {
		"spteBlackToolTip": "true",
		"spteFrenchFlag": "true"
	}
}
```

**Comment by webaxones** [comment]
Ah...
J'en ai un peu plus, mais ça m'étonne que ça plante le rangement... parce qu'en fait ce bug c'est un cas où je dois mal reranger les éléments dans mon "fix header"...
Je vais essayer ce soir avec tes paramètres pour voir.
```
{
	"spteBetterReadability": "false",
	"spteBlackToolTip": "true",
	"spteColorChar": "#ff00ff",
	"spteColorQuote": "#ff0000",
	"spteColorWord": "#ff0000",
	"spteFrenchFlag": "true",
	"spteGpcontentBig": "false",
	"spteGpcontentMaxWitdh": "",
	"spteOtherSlugs": ""
}```

**Comment by webaxones** [comment]
Bonsoir @jeherve 
Quand tu auras le temps, si tu en as le temps, pourrais-tu inspecter le h2 et me faire une copie d'écran comme ci-dessous pour que je vois comment sont imbriqués les tags et si la div.filter-toolbar est bien là.
Car j'ai fait pas mal de tests et je n'arrive toujours pas à reproduire le problème.
![image](https://user-images.githubusercontent.com/17084006/114772475-22c17800-9d6e-11eb-862a-e2e95fe98169.png)
Egalement, si tu as des erreurs dans la console...
Merci !
Loïc

**Comment by jeherve** [comment]
> inspecter le h2 et me faire une copie d'écran comme ci-dessous pour que je vois comment sont imbriqués les tags et si la div.filter-toolbar est bien là.

Sans l'extension: 

![image](https://user-images.githubusercontent.com/426388/114828038-b6746200-9dc9-11eb-9a47-76d2108a688b.png)

Avec:

![image](https://user-images.githubusercontent.com/426388/114828113-cee47c80-9dc9-11eb-9c69-911e42922c48.png)


> Egalement, si tu as des erreurs dans la console...

```
Error handling response: TypeError: Cannot read property 'after' of null
    at buildHeader (chrome-extension://phoglaigilljgehnhjfomdhkgokelgnk/spte.js:423:11)
    at launchProcess (chrome-extension://phoglaigilljgehnhjfomdhkgokelgnk/spte.js:564:3)
    at chrome-extension://phoglaigilljgehnhjfomdhkgokelgnk/spte.js:581:3
```

**Comment by papicx92** [comment]
Bonjour Loïc,
le bug est toujours présent chez moi, sous Firefox. 
je t’envoie les copies d’écran des codes sources avec et sans SPTE
![avec_spte](https://user-images.githubusercontent.com/80912550/116817873-d301ef80-ab68-11eb-9df6-c12de65ed05f.png)
![sans_spte](https://user-images.githubusercontent.com/80912550/116817878-d72e0d00-ab68-11eb-9af2-d654124d3e2d.png)

**Comment by papicx92** [comment]
![inspecteur_avec_spte](https://user-images.githubusercontent.com/80912550/116818050-ab5f5700-ab69-11eb-906d-68549817f1ec.png)

**Comment by papicx92** [comment]
![inspecteur_sans_spte](https://user-images.githubusercontent.com/80912550/116818110-efeaf280-ab69-11eb-89fe-ad6df9f2890a.png)

**Comment by papicx92** [comment]
voilà, si ça peut t’aider... 
quid si tu peux décaler la barre spte sous le H2, ça pourrait peut-être résoudre le souci. ?

**Comment by webaxones** [comment]
Bonjour Patrice,
Oui ça peut m'aider, je te remercie.
Il faut surtout que je trouve quelques heures à bloquer pour analyser ce problème mais je vais les trouver :)

**Comment by webaxones** [comment]
Juste par curiosité @papicx92 si tu supprimes l'extension du navigateur (pas désactive mais bien supprime) puis que tu la réinstalles, le bug est toujours présent ?

**Comment by papicx92** [comment]
Je vais faire ça et je te fais un retour. J'espère en fin de matinée. Pour info, j'ai fait l'essai en désactivant mon antivirus Avast, ça n'a rien changé. PapicxEnvoyé de mon Galaxy S8+ Free
-------- Message d'origine --------De : Loïc Antignac ***@***.***> Date : 03/05/2021  07:56  (GMT+01:00) À : webaxones/spte ***@***.***> Cc : papicx92 ***@***.***>, Mention ***@***.***> Objet : Re: [webaxones/spte] SPTE masque la ligne de recherche (#40) 

Juste par curiosité @papicx92 si tu supprimes l'extension du navigateur (pas désactive mais bien supprime) puis que tu la réinstalles, le bug est toujours présent ?

**Comment by papicx92** [comment]
Merci de l'information Loïc. ;-) PapicxEnvoyé de mon Galaxy S8+ Free
-------- Message d'origine --------De : Loïc Antignac ***@***.***> Date : 08/05/2021  10:26  (GMT+01:00) À : webaxones/spte ***@***.***> Cc : papicx92 ***@***.***>, Mention ***@***.***> Objet : Re: [webaxones/spte] SPTE masque la ligne de recherche (#40) 
Closed #40 via #45.
